// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1024","screenHeight":"576","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"haya-core","status":true,"description":"[0.3.2] Essential core for my plugins to MV.","parameters":{}},
{"name":"haya-el","status":true,"description":"[0.1.5] Essential methods to create HTML Elements","parameters":{}},
{"name":"haya-components","status":true,"description":"[0.1.3] Essential methods to create some components","parameters":{}},
{"name":"haya-particle","status":true,"description":"[0.1.1]","parameters":{}},
{"name":"haya-weather","status":true,"description":"[0.1.0] Weather System","parameters":{}},
{"name":"haya-map","status":true,"description":"[0.2.7] Haya Map","parameters":{}},
{"name":"haya-movement","status":true,"description":"[0.1.9] Haya Movement | Organic Movement","parameters":{}},
{"name":"haya-map-editor","status":true,"description":"[0.3.1] Haya Map Editor","parameters":{}},
{"name":"haya-cutscene","status":true,"description":"[0.1.1] Haya Cutscene","parameters":{}},
{"name":"haya-title","status":true,"description":"","parameters":{}}
];
