// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1024","screenHeight":"576","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"haya-core","status":true,"description":"[0.3.6] Essential core for my plugins to MV.","parameters":{}},
{"name":"haya-el","status":true,"description":"[0.1.5] Essential methods to create HTML Elements","parameters":{}},
{"name":"haya-components","status":true,"description":"[0.1.5] Methods to create HTMLElement components","parameters":{}},
{"name":"haya-controller","status":true,"description":"[0.1.1] Controller for elements","parameters":{}},
{"name":"haya-particle","status":true,"description":"[0.1.3] Particle System from Immersion Plugin","parameters":{}},
{"name":"haya-filters","status":true,"description":"[0.1.4] Filter System from Immersion Plugin","parameters":{}},
{"name":"haya-weather","status":true,"description":"[0.1.0] Weather System","parameters":{}},
{"name":"haya-map","status":true,"description":"[0.2.8] Haya Map","parameters":{}},
{"name":"haya-collision-draw","status":true,"description":"[0.1.0] Draw collision graphic over map","parameters":{}},
{"name":"haya-movement","status":true,"description":"[0.2.0] Haya Movement | Organic Movement","parameters":{}},
{"name":"haya-editor","status":true,"description":"[0.1.1] Editor components & modules","parameters":{}},
{"name":"haya-map-editor","status":false,"description":"[0.3.2] Haya Map Editor","parameters":{}},
{"name":"haya-sprite-editor","status":false,"description":"[0.1.0] Haya Sprite Editor","parameters":{}},
{"name":"haya-cutscene","status":true,"description":"[0.1.1] Haya Cutscene","parameters":{}},
{"name":"haya-title","status":true,"description":"","parameters":{}},
{"name":"haya-immersion","status":false,"description":"[0.2.2] Haya Immersion | Menu","parameters":{}}
];
